name: Deploy Jobs

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      action:
        description: "Run Terraform Apply or Destroy?"
        type: string
        required: false

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.SECRET_PRIME2 }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY2 }}
  AWS_REGION: us-east-1
  PUBLIC_KEY_CONTENT: ${{ secrets.PUBLIC_KEY_CONTENT }}

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0 # or the version you need

      - name: Run Terraform Init
        run: terraform init
      
      - name: Run Hidden files and folders
        run: ls -aR ~/

      - name: Run Terraform Plan
        run: terraform plan -var "public_key_content=${{ secrets.PUBLIC_KEY_CONTENT }}"

      - name: Run Terraform Deployment
        run: terraform ${{ github.event.inputs.action }} -auto-approve -var "public_key_content=${{ secrets.PUBLIC_KEY_CONTENT }}"
        if: ${{ github.event.inputs.action == 'apply' || github.event.inputs.action == 'destroy' }}
